### ISSUE TITLE
Auto Aim is really not accurate.

### ISSUE THREAD

**Issue by dirtbikerxz** [JCharante/SteamPowered#2]
Can you make auto aim more accurate. With auto aim on, the 15 balls per second is much less accurate than the previous 5 balls per second. Can you either make autoaim more accurate, (or better yet just for fun) include another option in settings to have "100 percent accuracy" no matter where you shoot from.

**Comment by JCharante** [comment]
I'll definitely take a look at how auto aim works, I think it may be shooting balls at a different speed but at the same rate.

---

Turns out the [randomness in autoaim](https://github.com/JCharante/SteamPowered/blob/master/src/RedRobot.java#L81) is just too aggressive. Without that, it gets 100% accuracy from most spots.

---

AutoAim has been improved in 74e4de8, but I'll look into adding the 100% accuracy as an option.

---

SATA Aim has been added in v2.4

As such, I will consider this issue solved.
